package tests;

/**
 *
 * @author
 * @version
 */
public class nbtest03 extends java.awt.Frame {

  /** Initializes the Form */
  public nbtest03() {
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    addWindowListener (new java.awt.event.WindowAdapter () {
        public void windowClosing (java.awt.event.WindowEvent evt) {
          exitForm (evt);
        }
      }
    );
    setLayout (new java.awt.BorderLayout ());

    jPanel1 = new com.sun.java.swing.JPanel ();
    jPanel1.setLayout (new java.awt.GridLayout (1, 2));

      jButton2 = new com.sun.java.swing.JButton ();
      jButton2.setText ("jButton2");
      jPanel1.add (jButton2);

      jButton3 = new com.sun.java.swing.JButton ();
      jButton3.setText ("OK");
      jButton3.setLabel ("OK");
      jButton3.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            exit (evt);
          }
        }
      );
      jPanel1.add (jButton3);

    add (jPanel1, "South");

  }//GEN-END:initComponents

  private void exit (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit
    // Add your handling code here:
    System.exit (0)
  }//GEN-LAST:event_exit


  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:exitForm
    System.exit (0);
  }//GEN-LAST:exitForm


// Variables declaration - do not modify//GEN-BEGIN:variables
  com.sun.java.swing.JPanel jPanel1;
  com.sun.java.swing.JButton jButton2;
  com.sun.java.swing.JButton jButton3;
// End of variables declaration//GEN-END:variables


  public static void main(java.lang.String[] args) {
    new nbtest03 ().show ();
  }

}
